name: clean-img
on:
  workflow_run:
    workflows:
      - build-images
    types:
      - completed
  workflow_dispatch:
    inputs:
      run_clean:
        description: "Run a clean up of test.libreelec.tv leaving only 4 of each .img"
        default: no_run_clean
        required: true
        type: choice
        options:
          - no_run_clean
          - run_clean
          - force_remove_le11
jobs:
  clean_img:
    runs-on: [self-hosted, scripts]

    steps:
      - name: log variables
        run: |
          echo "github.event.inputs.run_clean = ${{ github.event.inputs.run_clean }}"
          echo "github.event.workflow_run.event = ${{ github.event.workflow_run.event }}"

      - name: Force remove image files in the test.libreelec.tv 11.0 directory
        if: |
          (github.event.inputs.run_clean == 'force_remove_le11')
        run: |
          ssh -p ${{ secrets.NIGHTLY_HOST_PORT }} ${{ secrets.NIGHTLY_HOST_USERNAME }}@${{ secrets.NIGHTLY_HOST }} \
            "find ${{ secrets.NIGHTLY_UPLOAD_PATH }}/11.0 -type f rm {} \;"

      - name: Remove old image files in the test.libreelec.tv directory
        if: |
          (github.event.inputs.run_clean == 'run_clean') || 
          (github.event.workflow_run.event == 'schedule') || 
          (github.event.workflow_run.event == 'workflow_dispatch')
        run: |
          ssh -p ${{ secrets.NIGHTLY_HOST_PORT }} ${{ secrets.NIGHTLY_HOST_USERNAME }}@${{ secrets.NIGHTLY_HOST }} \
            "ls ${{ secrets.NIGHTLY_UPLOAD_PATH }}/*/*/*/LibreELEC-*.{img.gz,tar,ova}" < /dev/null | \
            sed 's#nightly-[0-9]*-[a-z0-9]*#nightly-\*#' | \
              sort | \
                uniq | \
                  while read le_pattern; do
                    ssh -p ${{ secrets.NIGHTLY_HOST_PORT }} ${{ secrets.NIGHTLY_HOST_USERNAME }}@${{ secrets.NIGHTLY_HOST }} \
                      "ls -t ${le_pattern}" < /dev/null | \
                        awk 'NR>2' | \
                          while read file; do
                            echo "Removing old image file ${file}" 
                            ssh -p ${{ secrets.NIGHTLY_HOST_PORT }} ${{ secrets.NIGHTLY_HOST_USERNAME }}@${{ secrets.NIGHTLY_HOST }} rm -f ${file} ${file}.sha256
                          done
                  done
          ssh -p ${{ secrets.NIGHTLY_HOST_PORT }} ${{ secrets.NIGHTLY_HOST_USERNAME }}@${{ secrets.NIGHTLY_HOST }} \
            "find ${{ secrets.NIGHTLY_UPLOAD_PATH }} -type f -size 0 -exec rm {} \;"
