name: tools-update-changelog
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  update_changelog:
    if: github.repository == 'LibreELEC/actions'
    runs-on: [self-hosted, scripts]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: "${{ github.repository_owner }}/actions"
          submodules: "true"
          path: "actions"

      - name: Update changelog at LibreELEC nightly repository
        run: |
          cd "actions/"
          ssh ${{ secrets.NIGHTLY_HOST_USERNAME }}@${{ secrets.NIGHTLY_HOST }} -p ${{ secrets.NIGHTLY_HOST_PORT }} \
            "bash -s" < ./scripts/update_changelog.sh

      - name: Update releases.json at LibreELEC nightly repository
        run: |
          scp -P ${{ secrets.NIGHTLY_HOST_PORT }} actions/scripts/remote/release-scripts/releases.py \
            ${{ secrets.NIGHTLY_HOST_USERNAME }}@${{ secrets.NIGHTLY_HOST }}:/tmp
          ssh ${{ secrets.NIGHTLY_HOST_USERNAME }}@${{ secrets.NIGHTLY_HOST }} -p ${{ secrets.NIGHTLY_HOST_PORT }} \
            "time python3 /tmp/releases.py -i /var/www/test/ -u https://test.libreelec.tv -o /var/www/test"
